import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { defineConfig, type Plugin } from 'vite'

/**
 * Emit a plain `<script>` rather than a module one.
 *
 * Vite writes `<script type="module" crossorigin>` whatever the output format, and that single
 * attribute is what stops the built game opening from `file://`: module scripts are fetched
 * under CORS rules on every scheme, and a `file://` origin is opaque, so the browser refuses
 * before it reads a byte. The bundle is already an IIFE, which needs none of that.
 *
 * `defer` keeps the original ordering guarantee — the script still runs after the document is
 * parsed, which is what `type="module"` was providing and what `#stage` depends on.
 */
function classicScriptTag(): Plugin {
  return {
    name: 'shear-line-classic-script',
    apply: 'build',
    enforce: 'post',
    transformIndexHtml(html) {
      return html.replace(/<script type="module" crossorigin src=/g, '<script defer src=')
    },
  }
}

/**
 * The build version, injected from package.json — DECISIONS D-126.
 *
 * A bug report used to carry the *save schema* version, which says nothing about which build the
 * bug is in: the schema changes about once a quarter and the game changes daily. Reading it from
 * `package.json` at build time means the number in a report is the number in the release list, and
 * there is one place it is written down.
 */
const VERSION = JSON.parse(readFileSync(resolve(import.meta.dirname, 'package.json'), 'utf8'))
  .version as string

/**
 * Emit `sw.js` with the built asset names baked in — DECISIONS D-162.
 *
 * The worker has to precache the hashed bundle to make a cold offline start work, and only the
 * build knows the hash — so the worker is written *by* the build, the same way `__APP_VERSION__`
 * is. Hand-rolled rather than a Workbox dependency because the whole requirement is one cache,
 * five entries and two strategies; the plugin below is smaller than a plugin's changelog.
 *
 * The strategies, chosen so an update can never be pinned out:
 *  - navigations go network-first (fresh index.html whenever there is a network, cached copy
 *    when there is none) — a service worker that serves a stale page forever is how a web game
 *    dies of its own offline support;
 *  - everything else is cache-first, because the bundle is content-hashed and immutable.
 *
 * The cache is named for the version; `activate` deletes every other, so updates converge.
 */
function serviceWorker(): Plugin {
  return {
    name: 'shear-line-service-worker',
    apply: 'build',
    generateBundle(_options, bundle) {
      const built = Object.keys(bundle)
        .filter((name) => name !== 'index.html')
        .map((name) => `./${name}`)
      const precache = [
        './',
        './manifest.webmanifest',
        './icons/icon-192.png',
        './icons/icon-512.png',
        './icons/icon-maskable-512.png',
        './icons/apple-touch-icon.png',
        ...built,
      ]
      const source = `/* Generated by vite.config.ts (serviceWorker) for v${VERSION} — do not edit. */
const CACHE = 'shearline-v${VERSION}'
const PRECACHE = ${JSON.stringify(precache, null, 2)}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)).then(() => self.skipWaiting()),
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return
  if (new URL(request.url).origin !== self.location.origin) return

  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone()
          caches.open(CACHE).then((cache) => cache.put('./', copy))
          return response
        })
        .catch(() => caches.match('./')),
    )
    return
  }

  event.respondWith(
    caches.match(request).then(
      (hit) =>
        hit ??
        fetch(request).then((response) => {
          if (response.ok) {
            const copy = response.clone()
            caches.open(CACHE).then((cache) => cache.put(request, copy))
          }
          return response
        }),
    ),
  )
})
`
      this.emitFile({ type: 'asset', fileName: 'sw.js', source })
    },
  }
}

export default defineConfig({
  define: { __APP_VERSION__: JSON.stringify(VERSION) },
  plugins: [classicScriptTag(), serviceWorker()],
  server: { port: 5173, strictPort: true },
  // Relative asset paths so `dist/` runs from a subdirectory as well as a domain root.
  base: './',
  build: {
    assetsDir: 'assets',
    target: 'es2022',
    /**
     * High enough to inline the two font weights as data URIs — DECISIONS D-146.
     *
     * Same reason as the IIFE below, and the same decision: `dist/` has to run from `file://`, and a
     * font requested from an opaque origin is blocked by CORS exactly like a module script is. A
     * separate `.woff2` would leave the game rendering in a fallback face for anyone who opened it
     * by double-clicking — which is precisely the machine-dependent layout D-146 exists to end.
     *
     * The subset weights are 5.7KB each. 12KB cleared them with room — and then the trophy art
     * arrived (D-159): thirty-four 256px PNGs, the largest just over 14KB, which must inline for
     * exactly the reason the fonts must. A separate PNG fetched from a `file://` page is
     * cross-origin, and drawing one taints the canvas — `getImageData` (which the grayscale
     * locked variants are built with) would throw for anyone who opened the game by
     * double-clicking. 20KB covers the whole set; nothing else the game ships is in that range.
     */
    assetsInlineLimit: 300000,
    // The trophy art and generated dungeon plates ride the bundle as data URIs. One file that
    // opens from a double-click beats a small file plus canvas-tainting image requests.
    chunkSizeWarningLimit: 3400,
    rollupOptions: {
      // The game, and only the game. `dev/audio-debug.html` is a bench instrument — the dev
      // server serves it from `dev/`, and it has no business in a shipped bundle. It also
      // cannot share one: an IIFE build takes a single input.
      input: { main: resolve(import.meta.dirname, 'index.html') },
      output: {
        /**
         * A classic script, not an ES module — `PHASES.md` Phase 14 requires `dist/` to run
         * from `file://` as well as from a static server, and relative paths alone do not get
         * you there. A `<script type="module">` is fetched under CORS rules whatever the
         * scheme, and every `file://` origin is opaque, so the browser blocks it before it
         * reads a byte: a blank canvas and a console error, on a bundle that is otherwise
         * perfectly good. An IIFE is a plain `<script>` and loads from anywhere.
         *
         * The cost is that code splitting has to go, so the audio engine is no longer a
         * separate chunk. On a 117 kB bundle that is not a trade worth arguing about, and
         * "the file I was sent opens when I double-click it" is worth a great deal.
         * See DECISIONS D-037.
         */
        format: 'iife',
      },
    },
  },
})
